name = "team-divider"
main = "src/index.js"
compatibility_date = "2023-12-01"

[env.production]
name = "team-divider"

# 如果需要使用Durable Objects，取消注释以下配置
# [[durable_objects.bindings]]
# name = "ROOM_STATE"
# class_name = "RoomState"

# 如果需要使用KV存储，取消注释以下配置
# [[kv_namespaces]]
# binding = "TEAM_DIVIDER_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
